#!/bin/bash

set -e

MY_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
PATH=${PATH}:${MY_ROOT}/vendor/bin:${MY_ROOT}/bin

install_deps
cd ${MY_ROOT}/packer && packer build frontend.json

echo "Sleeping 60s to make sure AMI is active..."
sleep 60
