#!/bin/bash

set -e

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

FRONTEND_AMI=$(aws --region us-west-2 \
                   ec2 describe-images \
                   --owners "self" \
                   --filters "Name=name,Values=frontend" \
                   --output text | grep IMAGES | awk '{ print $4 }')

aws --region us-west-2 \
    cloudformation create-stack --stack-name 'frontend' \
    --template-body "$(cat ${MY_DIR}/frontend.template)" \
    --parameters "ParameterKey=FrontendAMI,ParameterValue=${FRONTEND_AMI}" || \
aws --region us-west-2 \
    cloudformation update-stack --stack-name 'frontend' \
    --template-body "$(cat ${MY_DIR}/frontend.template)" \
    --parameters "ParameterKey=FrontendAMI,ParameterValue=${FRONTEND_AMI}"
